# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

commands:
  prepare_codeclimete_reporter:
    description: "Prepara CodeClimate reporter"
    steps:
      - run:
          name: Prepare CodeClimate Reporter
          command: |
            mkdir -p temp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            chmod +x /Library/Ruby/Gems/2.6.0
            ./cc-test-reporter before-build

  config_workspace:
    description: "Install or Restore configurations"
    steps:
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install Bundle if not exist in cache
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle
      - restore_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install Pods
          command: pod install
      - save_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
          paths: 
            - Pods/

  test:
    description: "Test aplication"
    parameters: 
      lane:
        type: string
    steps:
      - run: bundle exec fastlane << parameters.lane >>

jobs:
  build:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout
      - prepare_codeclimete_reporter
      - config_workspace

  test-domain-layer:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout
      - prepare_codeclimete_reporter
      - config_workspace
      - test:
          lane: "test_domain_layer"

  test-data-layer:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout
      - prepare_codeclimete_reporter
      - config_workspace
      - test:
          lane: "test_data_layer"

  test-presentation-layer:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout
      - prepare_codeclimete_reporter
      - config_workspace
      - test:
          lane: "test-presentation-layer"

  upload-coverage:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage ./report/cobertura.*.xml -p 2 -o tmp/cobertura.total.xml
            ./tmp/cc-test-reporter upload-coverage -i ./report/cobertura.total.xml

workflows:
  version: 2.1
  commit:
    jobs:
      - build
      - test-domain-layer:
          requires:
            - build
      - test-data-layer:
          requires: 
             - build
      - test-presentation-layer:
          requires: 
             - build
      - upload-coverage:
          requires:
             - test-domain-layer
             - test-data-layer
             - test-presentation-layer