# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 11 Pro Max (13.4.1) [7FDE8ED7-1356-4ECE-B82D-37733C1E55CB]" || true
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
            - build-temp-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.7.0" > ~/.ruby-version
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            sudo gem install bundler

      - run: bundle --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: pod install # Install CocoaPods dependencies
      - run:
          name: Prepare cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - run: fastlane test # Run tests using Fastlane

      - run:
          name: Submit to codeclimate
          command: ./cc-test-reporter after-build
      - save_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods/

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_test_results:
          path: fastlane/report.xml
      - store_artifacts:
          path: fastlane/report/
          destination: scan-output
