# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      
      - restore_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}

      - run:
          name: Configure Bundle
          command: |
            echo "ruby-2.7.0" > ~/.ruby-version
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            chmod +x /Library/Ruby/Gems/
            sudo gem install bundler
            bundle install
            

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /Library/Ruby/Gems/

      - run: 
          name: Install Pods
          command: pod install

      - run:
          name: Prepare CodeClimate Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build

      - run: fastlane test # Run tests using Fastlane

      - run:
          name: Submit to codeclimate
          command: ./cc-test-reporter after-build -t cobertura

      - save_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods/

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_test_results:
          path: fastlane/report.xml
      - store_artifacts:
          path: fastlane/report/
          destination: scan-output