# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout

      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      # Store bundle cache
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}

      - run: 
          name: Install Pods
          command: pod install
        
      - save_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods/

      - run:
          name: Prepare CodeClimate Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            chmod +x /Library/Ruby/Gems/2.6.0
            ./cc-test-reporter before-build

      - run: bundle exec fastlane test # Run tests using Fastlane

      - run:
          name: Submit to codeclimate
          command: ./cc-test-reporter after-build -t cobertura

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_test_results:
          path: fastlane/report.xml
      - store_artifacts:
          path: fastlane/report/
          destination: scan-output