name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fastlane
      run: sudo gem install fastlane -NV
    - name: Config Fastlane
      run: export PATH="$HOME/.fastlane/bin:$PATH" 
    - name: Run tests
      run: fastlane test
    
