name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Fastlane
      run: sudo gem install fastlane -NV
    - name: Install Bundler
      run: sudo gem install bundler
    - name: Install Gemfile
      run: bundle update && bundle install
    - name: Config Fastlane
      run: export PATH="$HOME/.fastlane/bin:$PATH" 
    - name: Run tests
      run: bundle exec fastlane test
    - uses: actions/upload-artifact@v1
        with:
          name: domain_test_report
          path: ./fastlane/domain/tests/report.junit
    - uses: actions/upload-artifact@v1
        with:
          name: data_test_report
          path: ./fastlane/data/tests/report.junit
    - uses: actions/upload-artifact@v1
        with:
          name: presentation_test_report
          path: ./fastlane/presentation/tests/report.junit
    
